---
title: "Discrete random variables"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm007 - October 23, 2018

## Overview

* Define random variables
* Distinguish between discrete and interval variables
* Identify discrete random variable distributions relevant to social science
* Review measures of central tendency and dispersion
* Define expected value and variance
* Define cumulative distribution functions (CDFs) for discrete random variables

## Before class

* Read [chapters 2-3 (Random Variables and Expectation) in *All of Statistics*](https://link-springer-com.proxy.uchicago.edu/book/10.1007%2F978-0-387-21736-9) (UChicago authentication required)
    * Focus primarily on content related to **discrete** random variables - we will cover continuous variables next week

## Slides and class materials

* [Slides](extras/cm007_slides.html)
* [Discrete random variables](rv-discrete.html)

## Additional resources

## What you need to do

