---
title: "Data objects/tidy data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm004 - October 11, 2018

## Overview

* Define a tibble
* Demonstrate how vectors can be read and parsed
* Define various data file formats and functions for importation
* Define tidy data and its characteristics
* Practice tidying data

## Before class

* Read Chapters 9-12 from [R for Data Science](http://r4ds.had.co.nz/)
* Read [Wickham, H. (2014). Tidy data. *Journal of Statistical Software*, 59(10), 1-23.](https://www.jstatsoft.org/article/view/v059i10)
    * Ignore the code examples - `plyr` and `reshape2` are no longer the dominant packages in R for reshaping and tidying data. Focus instead on the definition and types of "messy" datasets

## Slides and class materials

* [Importing data into R](https://cfss.uchicago.edu/datawrangle_import_functions.html)
* [Tidy data](https://cfss.uchicago.edu/datawrangle_tidy_data.html)
* [Data storage types](https://cfss.uchicago.edu/program_vectors.html)
* Vectors/matricies/arrays and linear algebra
* [Practice tidying data](https://cfss.uchicago.edu/datawrangle_tidy_exercise.html)

## What you need to do

* [Install and setup software](https://cfss.uchicago.edu/setup00.html)
* Complete [homework 01/02](hw02-wrangle-explore-data.html)
