---
title: "FAQ"
output: html_document
---

# What do I need for this course?

**You will need to bring a computer to class each day.** Class sessions are a mix of lecture, demonstration, and live coding. It is essential to have a computer so you can follow along and complete the exercises.

## Textbooks/Readings

* [R for Data Science](http://r4ds.had.co.nz/) -- Garrett Grolemund and Hadley Wickham
    * [Hardcover available for purchase online](https://www.amazon.com/R-Data-Science-Hadley-Wickham/dp/1491910399/ref=as_li_ss_tl?ie=UTF8&qid=1469550189&sr=8-1&keywords=R+for+data+science&linkCode=sl1&tag=devtools-20&linkId=6fe0069f9605cf847ed96c191f4e84dd)
    * Open-source online version is available for free

    > Completing the exercises in the book? No official solution manual exists, but several can be found online. I recommend [this version by Jeffrey B. Arnold](https://jrnold.github.io/r4ds-exercise-solutions/). Your exact solutions may vary, but these can be a good starting point.

### Additional resources

* [DataCamp](https://www.datacamp.com/home) - DataCamp offers interactive R and Python courses on topics in data science, statistics, and machine learning. These are a supplement to our primary textbook and lessons. Introductory DataCamp courses are free, whereas premium courses generally cost a fee. As a participant in this course, you have free access to all premium courses for the duration of the term. I will send you an email in the first week to activate your account if you wish to create one.
* [ggplot2: Elegant Graphics for Data Analysis, 2nd Edition](http://link.springer.com.proxy.uchicago.edu/book/10.1007/978-3-319-24277-4) -- Hadley Wickham
    * Excellent resource for the [`ggplot2`](https://cran.r-project.org/web/packages/ggplot2/index.html) graphics library.
* [Advanced R](http://adv-r.had.co.nz/) -- Hadley Wickham
    * Hardcover available online for around $55, but the online version is free
    * A deep dive into R as a programming language, not just a tool for data science. We will use some chapters in class, but most of this material is best covered on your own after completion of this course
* [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)
    * Printable cheat sheets for common R tasks and features
    * [Data import](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-import-cheatsheet.pdf)
    * [Data transformation](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-transformation-cheatsheet.pdf)
    * [Data visualization](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/ggplot2-cheatsheet-2.1.pdf)
    * [RStudio IDE](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/rstudio-IDE-cheatsheet.pdf)
    * [And more!](https://www.rstudio.com/resources/cheatsheets/)

## Software

By the end of the first week (or even better, before the course starts), you should install the following software on your computer:

* [R](https://www.r-project.org/) - easiest approach is to select [a pre-compiled binary appropriate for your operating system](https://cran.rstudio.com/).
* [RStudio's IDE](https://www.rstudio.com/products/RStudio/) - this is a powerful user interface for programming in R. You could use base R, but you would regret it.
* [Git](https://git-scm.com/) - Git is a [version control system](https://en.wikipedia.org/wiki/Version_control) which is used to manage projects and track changes in computer files. Once installed, it can be integrated into RStudio to manage your course assignments and other projects.

Comprehensive instructions for downloading and setting up this software can be found [here](https://cfss.uchicago.edu/setup00.html).

# How will I be evaluated?

Students will complete weekly problem sets with a combination of analytical and computational problems. Each problem set is worth 10 points. Final grades will be determined based on cumulative performance across the problem sets. Specific instructions for submitting homework assignments will be outlined in-class.

## Statement on Disabilities

If you need any special accommodations, please provide me (Dr. Soltoff) with a copy of your Accommodation Determination Letter (provided to you by the Student Disability Services office) as soon as possible so that you may discuss with me how your accommodations may be implemented in this course.
