---
title: "MACS 33001 - Mathematics and Statistics for Computational Social Science"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = FALSE, message = FALSE)
set.seed(1234)
```

* Instructor: [Benjamin Soltoff](http://www.bensoltoff.com), Lecturer in [Computational Social Science](http://macss.uchicago.edu)
* Meeting day/time: TTh 2-3:20pm (Social Sciences Research Building 107)
* Office hours: M 10-12pm (McGiffert House 209)
* Prerequisites: MACS 33000 (Computational Mathematics and Statistics Camp)
* Requirements: Bring your own laptop

## Course Description

This course aims to provide students with a core understanding of mathematics and statistics for computational social science. Students who complete this course should be prepared to take more advanced computational methods courses.

## Course Objectives

By the end of the course, students will:

* Construct and execute basic programs in R using elementary programming techniques and [`tidyverse`](http://tidyverse.org/) packages (e.g. loops, conditional statements, user-defined functions)
* Visualize information and data using appropriate graphical techniques
* Generate reproducible documents with [R Markdown](http://rmarkdown.rstudio.com/)
* Utilize professional document typesetting with mathematical notation via Markdown and $\LaTeX$
* Define key concepts related to theory of probability
* Identify and simulate random variables
* Calculate expected value and variance of random variables
* Write likelihood functions and optimize using a range of algorithms
* Conduct hypothesis tests
* Implement Bayesian methods of inference
* Evaluate via simulations the major properties and assumptions of ordinary least squares (OLS) regression
* Conduct inference and hypothesis testing for single and multivariable regression models
